version: '3.11.4'

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgresql
    volumes:
      - ./data/db:/var/lib/postgres/data
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=mejor_nines
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "80:80"
    depends_on:
      - db

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=mejor_nines
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    depends_on:
      - db