# Generated by Django 5.0.4 on 2024-06-12 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegalQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_quality", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.IntegerField()),
                ("commune", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("last_name_paternal", models.CharField(max_length=100)),
                ("last_name_maternal", models.CharField(max_length=100)),
                ("birthdate", models.DateField()),
                ("sex", models.BooleanField(default=True)),
                ("address", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Solicitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solicitor_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tribunal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tribunal_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Legal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proceedings", models.CharField(max_length=50)),
                ("cause_of_entry", models.CharField(max_length=200)),
                (
                    "legal_quality_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ReportsApp.legalquality",
                    ),
                ),
                (
                    "tribunal_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ReportsApp.tribunal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NNA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_nna", models.IntegerField(unique=True)),
                ("type_of_attention", models.BooleanField(default=True)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "legal_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ReportsApp.legal",
                    ),
                ),
                (
                    "location_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ReportsApp.location",
                    ),
                ),
                (
                    "user_FK",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ReportsApp.person",
                    ),
                ),
                (
                    "solicitor_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ReportsApp.solicitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True)),
                ("project_name", models.CharField(max_length=100)),
                (
                    "institution_FK",
                    models.ManyToManyField(
                        related_name="projects", to="ReportsApp.institution"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_entry", models.DateField()),
                ("date_of_exit", models.DateField(blank=True, null=True)),
                ("current_status", models.BooleanField(default=True)),
                (
                    "nna_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ReportsApp.nna"
                    ),
                ),
                (
                    "project_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ReportsApp.project",
                    ),
                ),
            ],
        ),
    ]
