# Generated by Django 5.0.4 on 2024-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ReportsApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legal",
            name="proceedings",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="legalquality",
            name="name_quality",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="commune",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="solicitor",
            name="solicitor_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tribunal",
            name="tribunal_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
