# Generated by Django 5.0.4 on 2024-06-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ReportsApp", "0002_alter_legal_proceedings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="commune",
            field=models.CharField(max_length=100),
        ),
    ]
